### PR TITLE
feat: words for FrontEnd v2 Standardization Revised copy

### PR DESCRIPTION
**Pull request by shermainelim**
Related to: https://www.notion.so/701364d4fbbf4ec1801b766c589973b9?v=24aa9675206d4da9a171ca4073d81b5b&p=c164596507ac48d28153524e72c50b15

This PR adds... 

- [x] I've kept this PR as small as possible (~600 lines) by splitting it into PRs with manageable chunks of code
- [x] I've requested reviews from 1-2 reviewers
- [ ] I've added [accessibility IDs](https://www.notion.so/dc5f4ce910f7431c84344ac79344e9f5?v=d487366816834dd4ab8dc12e0b5928f3) to my components
- [ ] I've added/updated unit/integration tests
- [ ] I've added/updated [e2e tests](https://www.notion.so/e2e-Documentation-a096d3e0bf75485e85ad692af8371ef3) for at least the happy flow
- [ ] I've added [Chinese translations for i18n setup](https://www.notion.so/Translations-Dev-Guide-8c1da838982a4f59a386ec96ac6780c8)
- [ ] I've added documentation in README/[Notion](https://www.notion.so/82b92fb1007640328dab9582c0a3694e?v=3b6ce48202cf40ad8450553799b13146)

### CODE REVIEW

**Review by ilhaoni — APPROVED** [review]
LGTM, verified with Notion story haha

Do remember to change this as well as this is not part of the code change here
```Sentence case instead of Title Case for All New device code```

**Comment by shermainelim** [comment]
> LGTM, verified with Notion story haha
> 
> Do remember to change this as well as this is not part of the code change here
> `Sentence case instead of Title Case for All New device code`

This was changed in AWS and verified with Eida prior Code Review. Checked against the Figma. 

@sebastianquek  please take note and change in production as previously discussed.

**Comment by ilhaoni** [comment]
Hmm, I think it would be better to leave a note on Notion to remind all the devs to update the value in production when we push to production, rather than pointing it out here. 

Do remember to delete the branches for PRs that have been merged and closed as well. (:

**Comment by shermainelim** [comment]
@ilhaoni  , have pm Sebastian on Slack but will post this on Notion as well now.

**Pull request merged**
