### PR TITLE
chore: add bypass check for android emulator

### PR DESCRIPTION
**Pull request by andrehadianto**
[Notion link](notion-link-here) 

This PR adds... 
- add scan bypass if device is using emulator

- [x] I've kept this PR as small as possible (~600 lines) by splitting it into PRs with manageable chunks of code
- [x] I've requested reviews from 1-2 reviewers
- [ ] I've added [accessibility IDs](https://www.notion.so/dc5f4ce910f7431c84344ac79344e9f5?v=d487366816834dd4ab8dc12e0b5928f3) to my components
- [ ] I've added/updated unit/integration tests
- [ ] I've added/updated [e2e tests](https://www.notion.so/e2e-Documentation-a096d3e0bf75485e85ad692af8371ef3) for at least the happy flow
- [ ] I've added [Chinese translations for i18n setup](https://www.notion.so/Translations-Dev-Guide-8c1da838982a4f59a386ec96ac6780c8)
- [ ] I've added documentation in README/[Notion](https://www.notion.so/82b92fb1007640328dab9582c0a3694e?v=3b6ce48202cf40ad8450553799b13146)

### CODE REVIEW

**Comment by sebastianquek** [comment]
@jedidiahkkh do try it out on your local emulator, let us know if it works fine!

**Comment by jedidiahkkh** [comment]
Tested on emulator with both virtual scene and also using laptop webcam and both works. Tested both QR code (for login to campaign) and barcode (for dispensing with NRIC).

Interestingly/strangely, for scanning barcodes with the emulator, the barcode is only detected when scanned vertically. It seems to be caused by expo code as `onBarCodeScanned` and `checkIfInInterestArea` are not even triggered when scanned NRIC horizontally. Not sure where we should document this in case anyone hits this issue in future.

**Review by jedidiahkkh — APPROVED** [review]
Tested on emulator with both virtual scene and also using laptop webcam and both works. Tested both QR code (for login to campaign) and barcode (for dispensing with NRIC).

Interestingly/strangely, for scanning barcodes with the emulator, the barcode is only detected when scanned vertically. It seems to be caused by expo code as `onBarCodeScanned` and `checkIfInInterestArea` are not even triggered when scanned NRIC horizontally. Not sure where we should document this in case anyone hits this issue in future.

**Comment by andrehadianto** [comment]
> Tested on emulator with both virtual scene and also using laptop webcam and both works. Tested both QR code (for login to campaign) and barcode (for dispensing with NRIC).
> 
> Interestingly/strangely, for scanning barcodes with the emulator, the barcode is only detected when scanned vertically. It seems to be caused by expo code as `onBarCodeScanned` and `checkIfInInterestArea` are not even triggered when scanned NRIC horizontally. Not sure where we should document this in case anyone hits this issue in future.

sounds good! will update the README with a link to a notion doc on this

**Pull request merged**
