### PR TITLE
Feat/fix cancel entry button

### PR DESCRIPTION
**Pull request by shermainelim**
For task `Cancel Entry button exceeding alert modal box for edge cases` : https://www.notion.so/701364d4fbbf4ec1801b766c589973b9?v=24aa9675206d4da9a171ca4073d81b5b&p=a66b9e15ddde431dac281f65b6c8d149

# Option 4. Using vertically stacked layouts for the button container so "Keep" and "Cancel entry" will be stacked only for small screens and large texts. 

If there is sufficient space for 2 columns on a single row it will display that.

Buttons have been scaled to same width.

Screenshot 2020-10-28 at 1 05 49 PM

Screenshot 2020-10-28 at 12 51 28 PM

### CODE REVIEW

**Comment by yongjiajie** [comment]
This is what I see on my phone:

IMAGE 2020-10-19 23:30:13
IMAGE 2020-10-19 23:30:16

**Comment by shermainelim** [comment]
what phone settings are u currently using?

**Comment by shermainelim** [comment]
is it set at max font size OR
set at max font size + max display size?

Option 2 will corrupt even for logout tab screen. please refer to PM

**Comment by shermainelim** [comment]
Pic 1 will scale to work at max font size + max display screen but is suggested Option 4 in notion, however already pointed out previously that logout tab will corrupt at font size. + max display screen in dev chat. At current , Option 2 was chosen. 

Screenshot 2020-10-20 at 12 05 30 AM

Screenshot 2020-10-20 at 12 05 37 AM

**Review by yongjiajie — APPROVED** [review]
The stacked buttons look good to me!

**Pull request merged**
