### PR TITLE
chore: freeze ubuntu image to 18.04 instead of latest

### PR DESCRIPTION
**Pull request by ilhaoni**
This PR specifies the ubuntu version to 18.04, instead of using ubuntu-latest.

This is due to actions/virtual-environments#1816

There is an update that would point ubuntu-latest to ubuntu-20.x, as we're currently using 18, I thought of just fixing this at 18 first.

We can revisit this again to update this to ubuntu-latest once things have stabilised after migration haha

- [ ] I've kept this PR as small as possible (~600 lines) by splitting it into PRs with manageable chunks of code
- [ ] I've requested reviews from 1-2 reviewers

### CODE REVIEW

**Review by sebastianquek — APPROVED** [review]

**Comment by ilhaoni** [comment]
Hmm... everything seemed to have passed, but there's still 3 more checks that uses ubuntu-latest... weird :/

**Comment by ilhaoni** [comment]
omg i think theres a bug sia... how ah @sebastianquek hahahaha 

the `Lint & Test (Ubuntu-latest, 10,12,13)` doesnt go away... so i cant approve it and merge D: 

it works if i dont edit the Test Different Development Environments ubuntu version

**Comment by sebastianquek** [comment]
I've updated the settings:
image

**Comment by ilhaoni** [comment]
OMG, how did you update the settings, teach me HAHA

**Pull request merged**
